name: CML Model Comparison Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  train-compare-report:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Train all models
        run: |
          python train_experiments.py
      
      - name: Compare models and generate report
        run: |
          python compare_models.py
      
      - name: Create CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install -g @dvcorg/cml
          
          echo "# 🏆 Rapport de Comparaison de Modèles - Exercice 3" >> report.md
          echo "" >> report.md
          
          echo "## 🎯 Meilleur Modèle Sélectionné" >> report.md
          echo "" >> report.md
          echo '```json' >> report.md
          cat experiments/best_model.json >> report.md
          echo '```' >> report.md
          echo "" >> report.md
          
          echo "## 📊 Comparaison des Accuracy" >> report.md
          echo "" >> report.md
          cml publish reports/accuracy_comparison.png --md >> report.md
          echo "" >> report.md
          
          echo "## 📈 Comparaison de Toutes les Métriques" >> report.md
          echo "" >> report.md
          cml publish reports/all_metrics_comparison.png --md >> report.md
          echo "" >> report.md
          
          echo "## 🔥 Heatmap des Performances" >> report.md
          echo "" >> report.md
          cml publish reports/performance_heatmap.png --md >> report.md
          echo "" >> report.md
          
          echo "## 📋 Résultats Détaillés" >> report.md
          echo "" >> report.md
          echo "<details>" >> report.md
          echo "<summary>Cliquez pour voir tous les résultats</summary>" >> report.md
          echo "" >> report.md
          echo '```json' >> report.md
          cat experiments/all_results.json >> report.md
          echo '```' >> report.md
          echo "</details>" >> report.md
          
          cml comment create report.md

